# Generated by Django 5.0.4 on 2024-05-07 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='учится'),
        ),
        migrations.AlterField(
            model_name='students',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='students/', verbose_name='Аватар'),
        ),
    ]
