# Generated by Django 5.0.4 on 2024-06-04 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='email',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='email'),
        ),
    ]
